version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .prod.env
    volumes:
      - ./database-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    restart: always
    env_file:
      - .prod.env
    container_name: gazprom-test
    ports:
      - "8000:8000"
    depends_on:
      - postgres
